encyclopedia/urls.py
from django.urls import path

from . import views

app_name = 'wiki'
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:title>",views.get_page, name="title"),
    path("search/",views.get_search_query, name="search_results"),
    path("new/",views.new_page, name="create"),
    path("random/",views.random_page, name ="random"),
    path("edit/",views.edit_page, name="edit"),
    path("save/",views.save_page, name="save")

]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/forms.py
from django import forms

#search form
class NewSearchForm(forms.Form):
    search = forms.CharField(label="Search",required= False,
    widget= forms.TextInput
    (attrs={'placeholder':'Search Encyclopedia'}))

#new page
class NewPageForm(forms.Form):
    pagename = forms.CharField(label="Title",required = True,help_text="<p class='text-secondary'>Please refer <a class='text-info' href = https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax> GitHub’s Markdown guide</a> </p>",
    widget= forms.TextInput
    (attrs={'placeholder':'Enter Title','class':'col-sm-11','style':'bottom:1rem'}))

    body = forms.CharField(label="Markdown content",required= False, 
    widget= forms.Textarea
    (attrs={'placeholder':'Enter markdown content','class':'col-sm-11','style':'top:2rem'}))

#edit page
class EditPageForm(forms.Form):
    pagename = forms.CharField(label="Title",disabled = False,required = False,
    widget= forms.HiddenInput
    (attrs={'class':'col-sm-12','style':'bottom:1rem'}))
   
    body = forms.CharField(label="Markdown content",help_text="<p class='text-secondary'>Please refer <a class='text-info' href = https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax> GitHub’s Markdown guide</a> </p>",
    widget= forms.Textarea
    (attrs={"rows":20, "cols":80,'class':'col-sm-11','style':'top:2rem'}))

encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse
from django.core.files import File
from . import util,forms
from random import choice


form = forms.NewSearchForm()


def index(request):

    '''
        display all the encyclopedia entries from disk

        steps:
        1. get all entries from list_entries() function of util.py
        2. redirect to index.html with entries for displaying the list. 
    '''
    entries =util.list_entries()

    return render(request, "encyclopedia/index.html", {
        "entries":entries ,
        "form":form
    })


def get_page(request,title):

    '''
        redirect to given title - encyclopedia page
        steps:
        1. get page contents from get_entry of util.py
        2. redirect to titlepage.html if content is found
        3. if content not found, redirect to error.html 

    '''
    page = util.get_entry(title)

    if page is None:
        # no page found 
        return render(request,"encyclopedia/error.html",{
            "form":form
        }) 
    
    # page found 
    return render(request,"encyclopedia/titlepage.html",{
        'title': title, 
        'content': page,
        "form":form,

    })




def get_search_query(request):
    '''
        this function handles the search request. 

        steps:
        1. get search query
        2. if exact match found for given query redirect to that page
        3. if not show list of all possible entries for that query

    '''
    if request.method == "GET":
        form = forms.NewSearchForm(request.GET)
      
        if form.is_valid():
            searchquery = form.cleaned_data["search"].lower()
            all_entries = util.list_entries()
            
       
            files=[filename for filename in all_entries if searchquery in filename.lower()]
    

            if len(files) == 0:

                '''
                    no matching filename found for the search query

                    So display "no results found"
                '''
                return render(request,"encyclopedia/search_results.html",{
                    'error' : "No results found",
                    "form":form
                })

            
            elif len(files) == 1 and files[0].lower() == searchquery:
                '''
                    found one matching filename for the search query 
                    and search query is same as entry page title. 

                    So redirect to get_page to display the page

                '''
                title = files[0]
                return get_page(request, title)

            
            else: 
                '''
                    multiple entry names found for query

                    steps:
                    1. traverse through the list of title names, 
                        and see if any title name is same search query 
                    2. if a match found redirect to get_page to display the page
                    3. if no match found redirect to search_results.html with list of all matching entries. 
                '''
                title = [filename for filename in files if searchquery == filename.lower()]

                if len(title)>0:
                    return get_page(request, title[0])
                else:
                    return render(request,"encyclopedia/search_results.html",{
                        'results':files,
                        "form":form

                    })

        else:
            # not a valid request
            return index(request)


    return index(request)


def new_page(request):
    '''
        create new page
        steps:

        1. get page title and body from NewPageForm
        2. check if the page title already exists in disk
        3. if page title exists- display error message
        4. if new page title - save new page and redirect to get_page with title name
    '''
    if request.method == "GET":
        create_form= forms.NewPageForm()
        return render(request, "encyclopedia/create_page.html",{
            "form":form,
            "create_form":create_form

        })
    else:
        create_form = forms.NewPageForm(request.POST)
        if create_form.is_valid():

            title = create_form.cleaned_data["pagename"]
            body = create_form.cleaned_data["body"]


            all_entries = util.list_entries()
            for filename in all_entries:
                if title.lower()== filename.lower():
                    create_form = forms.NewPageForm()
                    error_message="Page exists with the title '%s'. \n please try again with different title!" %filename
                    return render(request, "encyclopedia/create_page.html",{
                        "form":form,
                        "create_form":create_form,
                        "error":error_message
                        

                    })

            util.save_entry(title,body)
            return get_page(request, title)

        else:
            
            return render(request, "encyclopedia/create_page.html",{
            "form":form,
            "create_form":create_form

        })




def edit_page(request):
    '''
        edit page - pre-populate with page name and content
        
        steps:

        1. get page name from form and content from get_entry of util.py
        2. create a edit form object with initial value set as pagename and markdown content
        3. render to edit_page html file with pre-populated information.   

    '''
    pagename = request.POST.get("edit")

    content = util.get_entry(pagename)
    
    edit_form = forms.EditPageForm(initial={'pagename': pagename, 'body':content})
    if edit_form.is_valid():

        return render (request, "encyclopedia/edit_page.html",{
                "title": pagename,
                "form":form,
                "edit_form":edit_form
            
                

            })
    else:
        return render (request, "encyclopedia/edit_page.html",{
                "title": pagename,
                "form":form,
                "edit_form":edit_form        

        })
        

def save_page(request):
    '''
        save the edited page

        steps:
        1. get page name and markdown content from form
        2. save entry by calling save_entry function from util.py with page name and content.
        3. redirect to get_page function 

    '''
    edit_form = forms.EditPageForm(request.POST)

    if edit_form.is_valid():

        pagename = edit_form.cleaned_data["pagename"]
        content = edit_form.cleaned_data["body"]
        
        val = util.save_entry(pagename,content)

        return get_page(request, pagename)

    else:
        return render (request, "encyclopedia/edit_page.html",{
                "form":form,
                "edit_form":edit_form
            
        })


def random_page(request):

    '''
        display a random page from list_entries of util.py

    '''
    return get_page(request,choice( util.list_entries()))

encyclopedia/templates/encyclopedia/create_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New page
{% endblock %}
{% block nav-create %}<li class="nav-active">Create New Page</li>{% endblock %}
{% block body %}
    <!-- <h1 >Create page</h1> -->
    <h4 class="text-danger text-center  ">{{error}}</h4>
    <div >
        <form action="{% url 'wiki:create'  %}" method="POST"  >
            {% csrf_token %}          
            
            {{create_form}}
            
            <input id = "createpage" type="submit">
            
        </form> 
</div>

{% endblock %}

encyclopedia/templates/encyclopedia/edit_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit page
{% endblock %}

{% block body %}
  
    <h1 class="display-3 text-secondary">{{title}}</h1>
    
    <form action="{% url 'wiki:save'  %}" method="POST">
        {% csrf_token %}          
        
        {{edit_form}}
        
        <input id = "createpage" type="submit">
        
    </form> 


{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

<h1 class="text-danger display-1"> Error 404 : Page Not Found </h1>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}
{% block nav-home %}<li class="nav-active">Home</li>{% endblock %}
{% block body %}
    <div id="index">
        <!-- <h1>Pages</h1> -->
        
        <ul id ="show_list">
           
            {% for entry in entries %}
               
                <li><a href= "{% url 'wiki:title' title=entry %}">{{ entry }}</a> </li> 
              
            {% endfor %}
        </ul>
    
    </div>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        {% block nav %}
        <div class = "navigationbar">
            <nav class="navbar navbar-expand-lg nav-pills mb-3 ">
                <a class="navbar-brand" href="{% url 'wiki:index' %}"><h1>Wiki</h1></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ">
                    <li class="nav-item ">
                        {% block nav-home %}
                            <a class="nav-link" href="{% url 'wiki:index' %}">Home<span class="sr-only">(current)</span></a>
                        {% endblock %}
                    </li>
        
                    <li class="nav-item ">
                        {% block nav-create %}
                            <a class="nav-link " href = "{% url 'wiki:create' %}">Create New Page</a>
                        {% endblock %}
                    </li>
                    <li class="nav-item ">
                        {% block nav-random %}
                            <a class="nav-link"  href = "{% url 'wiki:random' %}">Random Page</a>
                        {% endblock %}
                    </li>
    
                    </ul>
                </div>
            </nav>
        </div>
        {% endblock %}
        <div class="row">
            <div class="sidebar col-lg-3 col-md-3">
                
                <form action="{% url 'wiki:search_results'  %}" method="GET" class="search">
                    
                    {{form}}

                    <input  id = "search" type="submit" value = "search">
                    
                </form>

                
            </div>
            <div class="main col-lg-9 col-md-9">
                {% block body %}
                
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/search_results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

<h1> Search results </h1>
<ul id ="search_result">
  
  <h3 class="text-danger ">{{error}}</h3>
    
    {% for result in results %}
      <li>
        <a href= "{% url 'wiki:title' title=result %}">{{result}}</a>
      </li>
    {% endfor %}
</ul>
{% endblock %}

encyclopedia/templates/encyclopedia/titlepage.html
{% extends "encyclopedia/layout.html" %}
{% block title %}

    {{title}}

{% endblock %}

{% block body %}


{% load md %}
    

    
    <form action="{% url 'wiki:edit'  %}" method = "POST">
        {% csrf_token %}
        
        {% with pagename=title %}    
        
        <button type="submit"  name = "edit" value="{{pagename}}" id ="edit">edit</button>
        
        {%endwith%}
        <h1 class="display-4 text-secondary">{{title}}</h1>

    </form>
    {{ content|markdown|safe }}

{% endblock %}